name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  release:
    uses: krill-software/.github/.github/workflows/krill-app-release.yml@main
    with:
      product-name: "Krill Terminal"
      example-file: "shell"
    secrets: inherit
    permissions:
      contents: write
